version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: veera24_postgres
    ports:
      - "5503:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: offboarding_db
    volumes:
      - pgdata24:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - offboarding-net

  backend:
    build: ./Backend
    container_name: veera24_backend
    ports:
      - "3074:3074"
    depends_on:
      - postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=admin123
      - PGDATABASE=offboarding_db
      - PGPORT=5432
      - PGHOST=postgres
    networks:
      - offboarding-net

  frontend:
    build: ./Frontend
    container_name: veera24_frontend
    ports:
      - "8265:80"
    depends_on:
      - backend
    networks:
      - offboarding-net

  hr:
    build: ./HR
    container_name: veera24_hr
    ports:
      - "8266:80"
    depends_on:
      - backend
    networks:
      - offboarding-net

volumes:
  pgdata24:

networks:
  offboarding-net:

